services:
- docker
addons:
  ssh_known_hosts:
  - 59.110.64.232
before_install:
- openssl aes-256-cbc -K $encrypted_3d7487df4e33_key -iv $encrypted_3d7487df4e33_iv
  -in ssh-key.enc -out ssh-key -d
- cp ssh-key ~/.ssh/id_rsa
script:
- "./build.sh"
after_script:
- chmod 600 ~/.ssh/id_rsa
- scp -o "StrictHostKeyChecking no" `./build.sh pack` root@59.110.64.232:/root/prj-pack-repo
notifications:
  email:
    on_success: always
    on_failure: always
