// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef USER_MANAGE_H
#define USER_MANAGE_H

#include <ngrest/common/Service.h>


struct register_req
{
    std::string reg_number;
    std::string reg_password;
    std::string reg_name;
};
typedef std::string register_resp;

struct hello_resp
{
    std::string hello;
};

struct login_random_resp
{
    std::string type;
    std::string status;
    std::string ssid;
};

struct login_req
{
    std::string login_id;
    std::string login_pwd;
};

struct login_resp
{
    std::string status;
    std::string ssid;
};

struct get_user_info_resp{
    std::string status;
    std::string name;
    std::string cash;
};


//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: user_manage
class user_manage: public ngrest::Service
{
public:
    // *method: GET
    // *location: /hello
    hello_resp proc_get_hello();


    // *method: POST
    // *location: /register
    register_resp proc_register(const register_req& text);

    // *method: POST
    // *location: /login
    login_resp proc_login(const login_req& text);

    // *method: GET
    // *location: /logoff/{ssid}
    std::string proc_logoff(std::string ssid);

    // *method: GET
    // *location: /login_random
    login_random_resp proc_login_random();

    // *method: GET
    // *location: /user_info/{ssid}
    get_user_info_resp proc_get_user_info(std::string ssid);
};


#endif // USER_MANAGE_H



