// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "user_manage.h"
#include "random_user.h"
#include "db_sqlite_user.h"

register_resp user_manage::proc_register(const register_req &text)
{
    register_resp ret;

    auto db_ret = db_sqlite_insert_user(text.reg_number, text.reg_password, text.reg_name);
    if (0 == db_ret)
        ret = "success";
    else if (1 == db_ret)
        ret = "exit";
    else
        ret = "fail";

    return ret;
}

hello_resp user_manage::proc_get_hello()
{
    hello_resp ret = {"hello mvc"};

    return ret;
}

login_random_resp user_manage::proc_login_random()
{
    login_random_resp ret;

    auto random_user_ssid = RandomUserGenerat();

    if (random_user_ssid.length() >= 0)
    {
        ret.status = "success";
        ret.type = "response";
        ret.ssid = random_user_ssid;
    }

    return ret;
}