// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef USER_MANAGE_H
#define USER_MANAGE_H

#include <ngrest/common/Service.h>


struct register_req
{
    std::string type;
    std::string action;
    std::string username;
    std::string password;
};
struct register_resp
{
    std::string type;
    std::string action;
    std::string status;
};

struct hello_resp
{
    std::string hello;
};

struct login_random_resp
{
    std::string type;
    std::string status;
    std::string ssid;
};

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: user_manage
class user_manage: public ngrest::Service
{
public:
    // *method: GET
    // *location: /hello
    hello_resp proc_get_hello();


    // *method: POST
    // *location: /register
    register_resp proc_register(const register_req& text);

    // *method: GET
    // *location: /login_random
    login_random_resp proc_login_random();
};


#endif // USER_MANAGE_H



